# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/proto/traffic_light/preprocessor_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/proto/traffic_light/preprocessor_config.proto',
  package='apollo.perception.traffic_light.preprocessor_config',
  syntax='proto2',
  serialized_pb=_b('\n@modules/perception/proto/traffic_light/preprocessor_config.proto\x12\x33\x61pollo.perception.traffic_light.preprocessor_config\"\x81\x02\n\x0cModelConfigs\x12\x1c\n\x04name\x18\x01 \x01(\t:\x0eTLPreprocessor\x12\x16\n\x07version\x18\x02 \x01(\t:\x05\x31.0.0\x12#\n\x16max_cached_lights_size\x18\x03 \x01(\x05:\x03\x31\x30\x30\x12#\n\x15projection_image_cols\x18\x04 \x01(\x05:\x04\x31\x39\x32\x30\x12#\n\x15projection_image_rows\x18\x05 \x01(\x05:\x04\x31\x30\x38\x30\x12\"\n\x15sync_interval_seconds\x18\x06 \x01(\x02:\x03\x30.1\x12(\n\x1bno_signals_interval_seconds\x18\x07 \x01(\x02:\x03\x30.5')
)




_MODELCONFIGS = _descriptor.Descriptor(
  name='ModelConfigs',
  full_name='apollo.perception.traffic_light.preprocessor_config.ModelConfigs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apollo.perception.traffic_light.preprocessor_config.ModelConfigs.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("TLPreprocessor").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='apollo.perception.traffic_light.preprocessor_config.ModelConfigs.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("1.0.0").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_cached_lights_size', full_name='apollo.perception.traffic_light.preprocessor_config.ModelConfigs.max_cached_lights_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projection_image_cols', full_name='apollo.perception.traffic_light.preprocessor_config.ModelConfigs.projection_image_cols', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1920,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projection_image_rows', full_name='apollo.perception.traffic_light.preprocessor_config.ModelConfigs.projection_image_rows', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1080,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sync_interval_seconds', full_name='apollo.perception.traffic_light.preprocessor_config.ModelConfigs.sync_interval_seconds', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_signals_interval_seconds', full_name='apollo.perception.traffic_light.preprocessor_config.ModelConfigs.no_signals_interval_seconds', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=379,
)

DESCRIPTOR.message_types_by_name['ModelConfigs'] = _MODELCONFIGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelConfigs = _reflection.GeneratedProtocolMessageType('ModelConfigs', (_message.Message,), dict(
  DESCRIPTOR = _MODELCONFIGS,
  __module__ = 'modules.perception.proto.traffic_light.preprocessor_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.traffic_light.preprocessor_config.ModelConfigs)
  ))
_sym_db.RegisterMessage(ModelConfigs)


# @@protoc_insertion_point(module_scope)
