# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/fuzz/routing/proto/routing_fuzz.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.routing.proto import routing_pb2 as modules_dot_routing_dot_proto_dot_routing__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/fuzz/routing/proto/routing_fuzz.proto',
  package='apollo.tools.fuzz.routing',
  syntax='proto2',
  serialized_pb=_b('\n3modules/tools/fuzz/routing/proto/routing_fuzz.proto\x12\x19\x61pollo.tools.fuzz.routing\x1a#modules/routing/proto/routing.proto\"M\n\x12RoutingFuzzMessage\x12\x37\n\x0frouting_request\x18\x01 \x02(\x0b\x32\x1e.apollo.routing.RoutingRequest')
  ,
  dependencies=[modules_dot_routing_dot_proto_dot_routing__pb2.DESCRIPTOR,])




_ROUTINGFUZZMESSAGE = _descriptor.Descriptor(
  name='RoutingFuzzMessage',
  full_name='apollo.tools.fuzz.routing.RoutingFuzzMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='routing_request', full_name='apollo.tools.fuzz.routing.RoutingFuzzMessage.routing_request', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=196,
)

_ROUTINGFUZZMESSAGE.fields_by_name['routing_request'].message_type = modules_dot_routing_dot_proto_dot_routing__pb2._ROUTINGREQUEST
DESCRIPTOR.message_types_by_name['RoutingFuzzMessage'] = _ROUTINGFUZZMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoutingFuzzMessage = _reflection.GeneratedProtocolMessageType('RoutingFuzzMessage', (_message.Message,), dict(
  DESCRIPTOR = _ROUTINGFUZZMESSAGE,
  __module__ = 'modules.tools.fuzz.routing.proto.routing_fuzz_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.fuzz.routing.RoutingFuzzMessage)
  ))
_sym_db.RegisterMessage(RoutingFuzzMessage)


# @@protoc_insertion_point(module_scope)
