# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/control/proto/control_conf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.canbus.proto import chassis_pb2 as modules_dot_canbus_dot_proto_dot_chassis__pb2
from modules.control.proto import pad_msg_pb2 as modules_dot_control_dot_proto_dot_pad__msg__pb2
from modules.control.proto import lat_controller_conf_pb2 as modules_dot_control_dot_proto_dot_lat__controller__conf__pb2
from modules.control.proto import lon_controller_conf_pb2 as modules_dot_control_dot_proto_dot_lon__controller__conf__pb2
from modules.control.proto import mpc_controller_conf_pb2 as modules_dot_control_dot_proto_dot_mpc__controller__conf__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/control/proto/control_conf.proto',
  package='apollo.control',
  syntax='proto2',
  serialized_pb=_b('\n(modules/control/proto/control_conf.proto\x12\x0e\x61pollo.control\x1a\"modules/canbus/proto/chassis.proto\x1a#modules/control/proto/pad_msg.proto\x1a/modules/control/proto/lat_controller_conf.proto\x1a/modules/control/proto/lon_controller_conf.proto\x1a/modules/control/proto/mpc_controller_conf.proto\"\xc2\x06\n\x0b\x43ontrolConf\x12\x16\n\x0e\x63ontrol_period\x18\x01 \x01(\x01\x12!\n\x19max_planning_interval_sec\x18\x02 \x01(\x01\x12$\n\x1cmax_planning_delay_threshold\x18\x03 \x01(\x01\x12\x38\n\x0c\x64riving_mode\x18\x04 \x01(\x0e\x32\".apollo.canbus.Chassis.DrivingMode\x12-\n\x06\x61\x63tion\x18\x05 \x01(\x0e\x32\x1d.apollo.control.DrivingAction\x12\x18\n\x10soft_estop_brake\x18\x06 \x01(\x01\x12\x46\n\x12\x61\x63tive_controllers\x18\x07 \x03(\x0e\x32*.apollo.control.ControlConf.ControllerType\x12\'\n\x1fmax_steering_percentage_allowed\x18\x08 \x01(\x05\x12\x1f\n\x17max_status_interval_sec\x18\t \x01(\x01\x12>\n\x13lat_controller_conf\x18\n \x01(\x0b\x32!.apollo.control.LatControllerConf\x12>\n\x13lon_controller_conf\x18\x0b \x01(\x0b\x32!.apollo.control.LonControllerConf\x12\x19\n\x11trajectory_period\x18\x0c \x01(\x01\x12\x16\n\x0e\x63hassis_period\x18\r \x01(\x01\x12\x1b\n\x13localization_period\x18\x0e \x01(\x01\x12 \n\x18minimum_speed_resolution\x18\x0f \x01(\x01\x12>\n\x13mpc_controller_conf\x18\x10 \x01(\x0b\x32!.apollo.control.MPCControllerConf\x12\x1b\n\x13query_relative_time\x18\x11 \x01(\x01\x12 \n\x18minimum_speed_protection\x18\x12 \x01(\x01\"L\n\x0e\x43ontrollerType\x12\x12\n\x0eLAT_CONTROLLER\x10\x00\x12\x12\n\x0eLON_CONTROLLER\x10\x01\x12\x12\n\x0eMPC_CONTROLLER\x10\x02')
  ,
  dependencies=[modules_dot_canbus_dot_proto_dot_chassis__pb2.DESCRIPTOR,modules_dot_control_dot_proto_dot_pad__msg__pb2.DESCRIPTOR,modules_dot_control_dot_proto_dot_lat__controller__conf__pb2.DESCRIPTOR,modules_dot_control_dot_proto_dot_lon__controller__conf__pb2.DESCRIPTOR,modules_dot_control_dot_proto_dot_mpc__controller__conf__pb2.DESCRIPTOR,])



_CONTROLCONF_CONTROLLERTYPE = _descriptor.EnumDescriptor(
  name='ControllerType',
  full_name='apollo.control.ControlConf.ControllerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAT_CONTROLLER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LON_CONTROLLER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MPC_CONTROLLER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1039,
  serialized_end=1115,
)
_sym_db.RegisterEnumDescriptor(_CONTROLCONF_CONTROLLERTYPE)


_CONTROLCONF = _descriptor.Descriptor(
  name='ControlConf',
  full_name='apollo.control.ControlConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_period', full_name='apollo.control.ControlConf.control_period', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_planning_interval_sec', full_name='apollo.control.ControlConf.max_planning_interval_sec', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_planning_delay_threshold', full_name='apollo.control.ControlConf.max_planning_delay_threshold', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='driving_mode', full_name='apollo.control.ControlConf.driving_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='apollo.control.ControlConf.action', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='soft_estop_brake', full_name='apollo.control.ControlConf.soft_estop_brake', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_controllers', full_name='apollo.control.ControlConf.active_controllers', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_steering_percentage_allowed', full_name='apollo.control.ControlConf.max_steering_percentage_allowed', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_status_interval_sec', full_name='apollo.control.ControlConf.max_status_interval_sec', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat_controller_conf', full_name='apollo.control.ControlConf.lat_controller_conf', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon_controller_conf', full_name='apollo.control.ControlConf.lon_controller_conf', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trajectory_period', full_name='apollo.control.ControlConf.trajectory_period', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chassis_period', full_name='apollo.control.ControlConf.chassis_period', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='localization_period', full_name='apollo.control.ControlConf.localization_period', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimum_speed_resolution', full_name='apollo.control.ControlConf.minimum_speed_resolution', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mpc_controller_conf', full_name='apollo.control.ControlConf.mpc_controller_conf', index=15,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='query_relative_time', full_name='apollo.control.ControlConf.query_relative_time', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimum_speed_protection', full_name='apollo.control.ControlConf.minimum_speed_protection', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLCONF_CONTROLLERTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=1115,
)

_CONTROLCONF.fields_by_name['driving_mode'].enum_type = modules_dot_canbus_dot_proto_dot_chassis__pb2._CHASSIS_DRIVINGMODE
_CONTROLCONF.fields_by_name['action'].enum_type = modules_dot_control_dot_proto_dot_pad__msg__pb2._DRIVINGACTION
_CONTROLCONF.fields_by_name['active_controllers'].enum_type = _CONTROLCONF_CONTROLLERTYPE
_CONTROLCONF.fields_by_name['lat_controller_conf'].message_type = modules_dot_control_dot_proto_dot_lat__controller__conf__pb2._LATCONTROLLERCONF
_CONTROLCONF.fields_by_name['lon_controller_conf'].message_type = modules_dot_control_dot_proto_dot_lon__controller__conf__pb2._LONCONTROLLERCONF
_CONTROLCONF.fields_by_name['mpc_controller_conf'].message_type = modules_dot_control_dot_proto_dot_mpc__controller__conf__pb2._MPCCONTROLLERCONF
_CONTROLCONF_CONTROLLERTYPE.containing_type = _CONTROLCONF
DESCRIPTOR.message_types_by_name['ControlConf'] = _CONTROLCONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlConf = _reflection.GeneratedProtocolMessageType('ControlConf', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCONF,
  __module__ = 'modules.control.proto.control_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.control.ControlConf)
  ))
_sym_db.RegisterMessage(ControlConf)


# @@protoc_insertion_point(module_scope)
