# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/control/proto/lon_controller_conf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.control.proto import calibration_table_pb2 as modules_dot_control_dot_proto_dot_calibration__table__pb2
from modules.control.proto import pid_conf_pb2 as modules_dot_control_dot_proto_dot_pid__conf__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/control/proto/lon_controller_conf.proto',
  package='apollo.control',
  syntax='proto2',
  serialized_pb=_b('\n/modules/control/proto/lon_controller_conf.proto\x12\x0e\x61pollo.control\x1a-modules/control/proto/calibration_table.proto\x1a$modules/control/proto/pid_conf.proto\"!\n\nFilterConf\x12\x13\n\x0b\x63utoff_freq\x18\x01 \x01(\x05\"\x94\x04\n\x11LonControllerConf\x12\n\n\x02ts\x18\x01 \x01(\x01\x12\x16\n\x0e\x62rake_deadzone\x18\x02 \x01(\x01\x12\x19\n\x11throttle_deadzone\x18\x03 \x01(\x01\x12$\n\x1cspeed_controller_input_limit\x18\x04 \x01(\x01\x12\x1b\n\x13station_error_limit\x18\x05 \x01(\x01\x12\x16\n\x0epreview_window\x18\x06 \x01(\x01\x12\x1f\n\x17standstill_acceleration\x18\x07 \x01(\x01\x12\x31\n\x10station_pid_conf\x18\x08 \x01(\x0b\x32\x17.apollo.control.PidConf\x12\x33\n\x12low_speed_pid_conf\x18\t \x01(\x0b\x32\x17.apollo.control.PidConf\x12\x34\n\x13high_speed_pid_conf\x18\n \x01(\x0b\x32\x17.apollo.control.PidConf\x12\x14\n\x0cswitch_speed\x18\x0b \x01(\x01\x12;\n\x17pitch_angle_filter_conf\x18\x0c \x01(\x0b\x32\x1a.apollo.control.FilterConf\x12S\n\x11\x63\x61libration_table\x18\r \x01(\x0b\x32\x38.apollo.control.calibrationtable.ControlCalibrationTable')
  ,
  dependencies=[modules_dot_control_dot_proto_dot_calibration__table__pb2.DESCRIPTOR,modules_dot_control_dot_proto_dot_pid__conf__pb2.DESCRIPTOR,])




_FILTERCONF = _descriptor.Descriptor(
  name='FilterConf',
  full_name='apollo.control.FilterConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cutoff_freq', full_name='apollo.control.FilterConf.cutoff_freq', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=185,
)


_LONCONTROLLERCONF = _descriptor.Descriptor(
  name='LonControllerConf',
  full_name='apollo.control.LonControllerConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='apollo.control.LonControllerConf.ts', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brake_deadzone', full_name='apollo.control.LonControllerConf.brake_deadzone', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='throttle_deadzone', full_name='apollo.control.LonControllerConf.throttle_deadzone', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed_controller_input_limit', full_name='apollo.control.LonControllerConf.speed_controller_input_limit', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='station_error_limit', full_name='apollo.control.LonControllerConf.station_error_limit', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preview_window', full_name='apollo.control.LonControllerConf.preview_window', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='standstill_acceleration', full_name='apollo.control.LonControllerConf.standstill_acceleration', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='station_pid_conf', full_name='apollo.control.LonControllerConf.station_pid_conf', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_speed_pid_conf', full_name='apollo.control.LonControllerConf.low_speed_pid_conf', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='high_speed_pid_conf', full_name='apollo.control.LonControllerConf.high_speed_pid_conf', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='switch_speed', full_name='apollo.control.LonControllerConf.switch_speed', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch_angle_filter_conf', full_name='apollo.control.LonControllerConf.pitch_angle_filter_conf', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calibration_table', full_name='apollo.control.LonControllerConf.calibration_table', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=720,
)

_LONCONTROLLERCONF.fields_by_name['station_pid_conf'].message_type = modules_dot_control_dot_proto_dot_pid__conf__pb2._PIDCONF
_LONCONTROLLERCONF.fields_by_name['low_speed_pid_conf'].message_type = modules_dot_control_dot_proto_dot_pid__conf__pb2._PIDCONF
_LONCONTROLLERCONF.fields_by_name['high_speed_pid_conf'].message_type = modules_dot_control_dot_proto_dot_pid__conf__pb2._PIDCONF
_LONCONTROLLERCONF.fields_by_name['pitch_angle_filter_conf'].message_type = _FILTERCONF
_LONCONTROLLERCONF.fields_by_name['calibration_table'].message_type = modules_dot_control_dot_proto_dot_calibration__table__pb2._CONTROLCALIBRATIONTABLE
DESCRIPTOR.message_types_by_name['FilterConf'] = _FILTERCONF
DESCRIPTOR.message_types_by_name['LonControllerConf'] = _LONCONTROLLERCONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilterConf = _reflection.GeneratedProtocolMessageType('FilterConf', (_message.Message,), dict(
  DESCRIPTOR = _FILTERCONF,
  __module__ = 'modules.control.proto.lon_controller_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.control.FilterConf)
  ))
_sym_db.RegisterMessage(FilterConf)

LonControllerConf = _reflection.GeneratedProtocolMessageType('LonControllerConf', (_message.Message,), dict(
  DESCRIPTOR = _LONCONTROLLERCONF,
  __module__ = 'modules.control.proto.lon_controller_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.control.LonControllerConf)
  ))
_sym_db.RegisterMessage(LonControllerConf)


# @@protoc_insertion_point(module_scope)
