# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/dp_poly_path_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.planning.proto import waypoint_sampler_config_pb2 as modules_dot_planning_dot_proto_dot_waypoint__sampler__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/dp_poly_path_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n0modules/planning/proto/dp_poly_path_config.proto\x12\x0f\x61pollo.planning\x1a\x34modules/planning/proto/waypoint_sampler_config.proto\"\x83\x04\n\x10\x44pPolyPathConfig\x12G\n\x17waypoint_sampler_config\x18\x01 \x01(\x0b\x32&.apollo.planning.WaypointSamplerConfig\x12\x1f\n\x12\x65val_time_interval\x18\x02 \x01(\x01:\x03\x30.1\x12\x1c\n\x0fpath_resolution\x18\x03 \x01(\x01:\x03\x30.1\x12$\n\x18obstacle_ignore_distance\x18\x04 \x01(\x01:\x02\x32\x30\x12(\n\x1bobstacle_collision_distance\x18\x05 \x01(\x01:\x03\x30.2\x12!\n\x16obstacle_risk_distance\x18\x06 \x01(\x01:\x01\x32\x12%\n\x17obstacle_collision_cost\x18\x07 \x01(\x01:\x04\x31\x30\x30\x30\x12\x13\n\x0bpath_l_cost\x18\x08 \x01(\x01\x12\x14\n\x0cpath_dl_cost\x18\t \x01(\x01\x12\x15\n\rpath_ddl_cost\x18\n \x01(\x01\x12\x1c\n\x14path_l_cost_param_l0\x18\x0b \x01(\x01\x12\x1b\n\x13path_l_cost_param_b\x18\x0c \x01(\x01\x12\x1b\n\x13path_l_cost_param_k\x18\r \x01(\x01\x12\x1a\n\x12path_out_lane_cost\x18\x0e \x01(\x01\x12\x17\n\x0fpath_end_l_cost\x18\x0f \x01(\x01')
  ,
  dependencies=[modules_dot_planning_dot_proto_dot_waypoint__sampler__config__pb2.DESCRIPTOR,])




_DPPOLYPATHCONFIG = _descriptor.Descriptor(
  name='DpPolyPathConfig',
  full_name='apollo.planning.DpPolyPathConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='waypoint_sampler_config', full_name='apollo.planning.DpPolyPathConfig.waypoint_sampler_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_time_interval', full_name='apollo.planning.DpPolyPathConfig.eval_time_interval', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_resolution', full_name='apollo.planning.DpPolyPathConfig.path_resolution', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacle_ignore_distance', full_name='apollo.planning.DpPolyPathConfig.obstacle_ignore_distance', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(20),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacle_collision_distance', full_name='apollo.planning.DpPolyPathConfig.obstacle_collision_distance', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacle_risk_distance', full_name='apollo.planning.DpPolyPathConfig.obstacle_risk_distance', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacle_collision_cost', full_name='apollo.planning.DpPolyPathConfig.obstacle_collision_cost', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1000),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_l_cost', full_name='apollo.planning.DpPolyPathConfig.path_l_cost', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_dl_cost', full_name='apollo.planning.DpPolyPathConfig.path_dl_cost', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_ddl_cost', full_name='apollo.planning.DpPolyPathConfig.path_ddl_cost', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_l_cost_param_l0', full_name='apollo.planning.DpPolyPathConfig.path_l_cost_param_l0', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_l_cost_param_b', full_name='apollo.planning.DpPolyPathConfig.path_l_cost_param_b', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_l_cost_param_k', full_name='apollo.planning.DpPolyPathConfig.path_l_cost_param_k', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_out_lane_cost', full_name='apollo.planning.DpPolyPathConfig.path_out_lane_cost', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_end_l_cost', full_name='apollo.planning.DpPolyPathConfig.path_end_l_cost', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=639,
)

_DPPOLYPATHCONFIG.fields_by_name['waypoint_sampler_config'].message_type = modules_dot_planning_dot_proto_dot_waypoint__sampler__config__pb2._WAYPOINTSAMPLERCONFIG
DESCRIPTOR.message_types_by_name['DpPolyPathConfig'] = _DPPOLYPATHCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DpPolyPathConfig = _reflection.GeneratedProtocolMessageType('DpPolyPathConfig', (_message.Message,), dict(
  DESCRIPTOR = _DPPOLYPATHCONFIG,
  __module__ = 'modules.planning.proto.dp_poly_path_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.DpPolyPathConfig)
  ))
_sym_db.RegisterMessage(DpPolyPathConfig)


# @@protoc_insertion_point(module_scope)
