# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/lattice_structure.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/lattice_structure.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n.modules/planning/proto/lattice_structure.proto\x12\x0f\x61pollo.planning\":\n\rPathTimePoint\x12\t\n\x01t\x18\x01 \x01(\x01\x12\t\n\x01s\x18\x02 \x01(\x01\x12\x13\n\x0bobstacle_id\x18\x04 \x01(\t\"U\n\x0bSamplePoint\x12\x37\n\x0fpath_time_point\x18\x01 \x01(\x0b\x32\x1e.apollo.planning.PathTimePoint\x12\r\n\x05ref_v\x18\x02 \x01(\x01\"\xcb\x02\n\x10PathTimeObstacle\x12\x13\n\x0bobstacle_id\x18\x01 \x01(\t\x12\x33\n\x0b\x62ottom_left\x18\x02 \x01(\x0b\x32\x1e.apollo.planning.PathTimePoint\x12\x32\n\nupper_left\x18\x03 \x01(\x0b\x32\x1e.apollo.planning.PathTimePoint\x12\x33\n\x0bupper_right\x18\x04 \x01(\x0b\x32\x1e.apollo.planning.PathTimePoint\x12\x34\n\x0c\x62ottom_right\x18\x05 \x01(\x0b\x32\x1e.apollo.planning.PathTimePoint\x12\x12\n\ntime_lower\x18\x06 \x01(\x01\x12\x12\n\ntime_upper\x18\x07 \x01(\x01\x12\x12\n\npath_lower\x18\x08 \x01(\x01\x12\x12\n\npath_upper\x18\t \x01(\x01\"g\n\tStopPoint\x12\t\n\x01s\x18\x01 \x02(\x01\x12\x33\n\x04type\x18\x02 \x02(\x0e\x32\x1f.apollo.planning.StopPoint.Type:\x04HARD\"\x1a\n\x04Type\x12\x08\n\x04HARD\x10\x00\x12\x08\n\x04SOFT\x10\x01\"V\n\x0ePlanningTarget\x12.\n\nstop_point\x18\x01 \x01(\x0b\x32\x1a.apollo.planning.StopPoint\x12\x14\n\x0c\x63ruise_speed\x18\x02 \x01(\x01')
)



_STOPPOINT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='apollo.planning.StopPoint.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=625,
  serialized_end=651,
)
_sym_db.RegisterEnumDescriptor(_STOPPOINT_TYPE)


_PATHTIMEPOINT = _descriptor.Descriptor(
  name='PathTimePoint',
  full_name='apollo.planning.PathTimePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='apollo.planning.PathTimePoint.t', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='apollo.planning.PathTimePoint.s', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obstacle_id', full_name='apollo.planning.PathTimePoint.obstacle_id', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=125,
)


_SAMPLEPOINT = _descriptor.Descriptor(
  name='SamplePoint',
  full_name='apollo.planning.SamplePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path_time_point', full_name='apollo.planning.SamplePoint.path_time_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ref_v', full_name='apollo.planning.SamplePoint.ref_v', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=212,
)


_PATHTIMEOBSTACLE = _descriptor.Descriptor(
  name='PathTimeObstacle',
  full_name='apollo.planning.PathTimeObstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obstacle_id', full_name='apollo.planning.PathTimeObstacle.obstacle_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bottom_left', full_name='apollo.planning.PathTimeObstacle.bottom_left', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upper_left', full_name='apollo.planning.PathTimeObstacle.upper_left', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upper_right', full_name='apollo.planning.PathTimeObstacle.upper_right', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bottom_right', full_name='apollo.planning.PathTimeObstacle.bottom_right', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_lower', full_name='apollo.planning.PathTimeObstacle.time_lower', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_upper', full_name='apollo.planning.PathTimeObstacle.time_upper', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_lower', full_name='apollo.planning.PathTimeObstacle.path_lower', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path_upper', full_name='apollo.planning.PathTimeObstacle.path_upper', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=546,
)


_STOPPOINT = _descriptor.Descriptor(
  name='StopPoint',
  full_name='apollo.planning.StopPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='apollo.planning.StopPoint.s', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='apollo.planning.StopPoint.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STOPPOINT_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=651,
)


_PLANNINGTARGET = _descriptor.Descriptor(
  name='PlanningTarget',
  full_name='apollo.planning.PlanningTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stop_point', full_name='apollo.planning.PlanningTarget.stop_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cruise_speed', full_name='apollo.planning.PlanningTarget.cruise_speed', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=739,
)

_SAMPLEPOINT.fields_by_name['path_time_point'].message_type = _PATHTIMEPOINT
_PATHTIMEOBSTACLE.fields_by_name['bottom_left'].message_type = _PATHTIMEPOINT
_PATHTIMEOBSTACLE.fields_by_name['upper_left'].message_type = _PATHTIMEPOINT
_PATHTIMEOBSTACLE.fields_by_name['upper_right'].message_type = _PATHTIMEPOINT
_PATHTIMEOBSTACLE.fields_by_name['bottom_right'].message_type = _PATHTIMEPOINT
_STOPPOINT.fields_by_name['type'].enum_type = _STOPPOINT_TYPE
_STOPPOINT_TYPE.containing_type = _STOPPOINT
_PLANNINGTARGET.fields_by_name['stop_point'].message_type = _STOPPOINT
DESCRIPTOR.message_types_by_name['PathTimePoint'] = _PATHTIMEPOINT
DESCRIPTOR.message_types_by_name['SamplePoint'] = _SAMPLEPOINT
DESCRIPTOR.message_types_by_name['PathTimeObstacle'] = _PATHTIMEOBSTACLE
DESCRIPTOR.message_types_by_name['StopPoint'] = _STOPPOINT
DESCRIPTOR.message_types_by_name['PlanningTarget'] = _PLANNINGTARGET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PathTimePoint = _reflection.GeneratedProtocolMessageType('PathTimePoint', (_message.Message,), dict(
  DESCRIPTOR = _PATHTIMEPOINT,
  __module__ = 'modules.planning.proto.lattice_structure_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.PathTimePoint)
  ))
_sym_db.RegisterMessage(PathTimePoint)

SamplePoint = _reflection.GeneratedProtocolMessageType('SamplePoint', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEPOINT,
  __module__ = 'modules.planning.proto.lattice_structure_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.SamplePoint)
  ))
_sym_db.RegisterMessage(SamplePoint)

PathTimeObstacle = _reflection.GeneratedProtocolMessageType('PathTimeObstacle', (_message.Message,), dict(
  DESCRIPTOR = _PATHTIMEOBSTACLE,
  __module__ = 'modules.planning.proto.lattice_structure_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.PathTimeObstacle)
  ))
_sym_db.RegisterMessage(PathTimeObstacle)

StopPoint = _reflection.GeneratedProtocolMessageType('StopPoint', (_message.Message,), dict(
  DESCRIPTOR = _STOPPOINT,
  __module__ = 'modules.planning.proto.lattice_structure_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.StopPoint)
  ))
_sym_db.RegisterMessage(StopPoint)

PlanningTarget = _reflection.GeneratedProtocolMessageType('PlanningTarget', (_message.Message,), dict(
  DESCRIPTOR = _PLANNINGTARGET,
  __module__ = 'modules.planning.proto.lattice_structure_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.PlanningTarget)
  ))
_sym_db.RegisterMessage(PlanningTarget)


# @@protoc_insertion_point(module_scope)
