# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/planner_open_space_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/planner_open_space_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n6modules/planning/proto/planner_open_space_config.proto\x12\x0f\x61pollo.planning\"6\n\x16PlannerOpenSpaceConfig\x12\x1c\n\x10planning_horizon\x18\x01 \x01(\r:\x02\x31\x30')
)




_PLANNEROPENSPACECONFIG = _descriptor.Descriptor(
  name='PlannerOpenSpaceConfig',
  full_name='apollo.planning.PlannerOpenSpaceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='planning_horizon', full_name='apollo.planning.PlannerOpenSpaceConfig.planning_horizon', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['PlannerOpenSpaceConfig'] = _PLANNEROPENSPACECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlannerOpenSpaceConfig = _reflection.GeneratedProtocolMessageType('PlannerOpenSpaceConfig', (_message.Message,), dict(
  DESCRIPTOR = _PLANNEROPENSPACECONFIG,
  __module__ = 'modules.planning.proto.planner_open_space_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.PlannerOpenSpaceConfig)
  ))
_sym_db.RegisterMessage(PlannerOpenSpaceConfig)


# @@protoc_insertion_point(module_scope)
