# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/st_boundary_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/st_boundary_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n/modules/planning/proto/st_boundary_config.proto\x12\x0f\x61pollo.planning\"\xc0\x03\n\x10StBoundaryConfig\x12\x1c\n\x0f\x62oundary_buffer\x18\x01 \x01(\x01:\x03\x30.1\x12\x32\n%high_speed_centric_acceleration_limit\x18\x02 \x01(\x01:\x03\x31.2\x12\x31\n$low_speed_centric_acceleration_limit\x18\x03 \x01(\x01:\x03\x31.4\x12 \n\x14high_speed_threshold\x18\x04 \x01(\x01:\x02\x32\x30\x12\x1e\n\x13low_speed_threshold\x18\x05 \x01(\x01:\x01\x37\x12\x1c\n\rminimal_kappa\x18\x06 \x01(\x01:\x05\x31\x65-05\x12\x1a\n\x0fpoint_extension\x18\x07 \x01(\x01:\x01\x31\x12\x19\n\x0clowest_speed\x18\x08 \x01(\x01:\x03\x32.5\x12\"\n\x17num_points_to_avg_kappa\x18\t \x01(\r:\x01\x34\x12$\n\x1cstatic_obs_nudge_speed_ratio\x18\n \x01(\x01\x12%\n\x1d\x64ynamic_obs_nudge_speed_ratio\x18\x0b \x01(\x01\x12\x1f\n\x17\x63\x65ntri_jerk_speed_coeff\x18\x0c \x01(\x01')
)




_STBOUNDARYCONFIG = _descriptor.Descriptor(
  name='StBoundaryConfig',
  full_name='apollo.planning.StBoundaryConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boundary_buffer', full_name='apollo.planning.StBoundaryConfig.boundary_buffer', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='high_speed_centric_acceleration_limit', full_name='apollo.planning.StBoundaryConfig.high_speed_centric_acceleration_limit', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_speed_centric_acceleration_limit', full_name='apollo.planning.StBoundaryConfig.low_speed_centric_acceleration_limit', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1.4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='high_speed_threshold', full_name='apollo.planning.StBoundaryConfig.high_speed_threshold', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(20),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_speed_threshold', full_name='apollo.planning.StBoundaryConfig.low_speed_threshold', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(7),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimal_kappa', full_name='apollo.planning.StBoundaryConfig.minimal_kappa', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1e-05),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_extension', full_name='apollo.planning.StBoundaryConfig.point_extension', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lowest_speed', full_name='apollo.planning.StBoundaryConfig.lowest_speed', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_points_to_avg_kappa', full_name='apollo.planning.StBoundaryConfig.num_points_to_avg_kappa', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='static_obs_nudge_speed_ratio', full_name='apollo.planning.StBoundaryConfig.static_obs_nudge_speed_ratio', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dynamic_obs_nudge_speed_ratio', full_name='apollo.planning.StBoundaryConfig.dynamic_obs_nudge_speed_ratio', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='centri_jerk_speed_coeff', full_name='apollo.planning.StBoundaryConfig.centri_jerk_speed_coeff', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=517,
)

DESCRIPTOR.message_types_by_name['StBoundaryConfig'] = _STBOUNDARYCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StBoundaryConfig = _reflection.GeneratedProtocolMessageType('StBoundaryConfig', (_message.Message,), dict(
  DESCRIPTOR = _STBOUNDARYCONFIG,
  __module__ = 'modules.planning.proto.st_boundary_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.StBoundaryConfig)
  ))
_sym_db.RegisterMessage(StBoundaryConfig)


# @@protoc_insertion_point(module_scope)
