# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/proto/waypoint_sampler_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/planning/proto/waypoint_sampler_config.proto',
  package='apollo.planning',
  syntax='proto2',
  serialized_pb=_b('\n4modules/planning/proto/waypoint_sampler_config.proto\x12\x0f\x61pollo.planning\"\x84\x02\n\x15WaypointSamplerConfig\x12\'\n\x1csample_points_num_each_level\x18\x01 \x01(\r:\x01\x39\x12\x1b\n\x0fstep_length_max\x18\x02 \x01(\x01:\x02\x31\x35\x12\x1a\n\x0fstep_length_min\x18\x03 \x01(\x01:\x01\x38\x12\"\n\x15lateral_sample_offset\x18\x04 \x01(\x01:\x03\x30.5\x12!\n\x14lateral_adjust_coeff\x18\x05 \x01(\x01:\x03\x30.5\x12\x19\n\x11sidepass_distance\x18\x06 \x01(\x01\x12\'\n\x1fnavigator_sample_num_each_level\x18\x07 \x01(\r')
)




_WAYPOINTSAMPLERCONFIG = _descriptor.Descriptor(
  name='WaypointSamplerConfig',
  full_name='apollo.planning.WaypointSamplerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_points_num_each_level', full_name='apollo.planning.WaypointSamplerConfig.sample_points_num_each_level', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=9,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step_length_max', full_name='apollo.planning.WaypointSamplerConfig.step_length_max', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(15),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step_length_min', full_name='apollo.planning.WaypointSamplerConfig.step_length_min', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(8),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lateral_sample_offset', full_name='apollo.planning.WaypointSamplerConfig.lateral_sample_offset', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lateral_adjust_coeff', full_name='apollo.planning.WaypointSamplerConfig.lateral_adjust_coeff', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sidepass_distance', full_name='apollo.planning.WaypointSamplerConfig.sidepass_distance', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='navigator_sample_num_each_level', full_name='apollo.planning.WaypointSamplerConfig.navigator_sample_num_each_level', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=334,
)

DESCRIPTOR.message_types_by_name['WaypointSamplerConfig'] = _WAYPOINTSAMPLERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WaypointSamplerConfig = _reflection.GeneratedProtocolMessageType('WaypointSamplerConfig', (_message.Message,), dict(
  DESCRIPTOR = _WAYPOINTSAMPLERCONFIG,
  __module__ = 'modules.planning.proto.waypoint_sampler_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.WaypointSamplerConfig)
  ))
_sym_db.RegisterMessage(WaypointSamplerConfig)


# @@protoc_insertion_point(module_scope)
