# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/fuzz/planning/proto/std_planning_fuzz.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.canbus.proto import chassis_pb2 as modules_dot_canbus_dot_proto_dot_chassis__pb2
from modules.localization.proto import localization_pb2 as modules_dot_localization_dot_proto_dot_localization__pb2
from modules.routing.proto import routing_pb2 as modules_dot_routing_dot_proto_dot_routing__pb2
from modules.prediction.proto import prediction_obstacle_pb2 as modules_dot_prediction_dot_proto_dot_prediction__obstacle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/fuzz/planning/proto/std_planning_fuzz.proto',
  package='apollo.tools.fuzz.planning',
  syntax='proto2',
  serialized_pb=_b('\n9modules/tools/fuzz/planning/proto/std_planning_fuzz.proto\x12\x1a\x61pollo.tools.fuzz.planning\x1a\"modules/canbus/proto/chassis.proto\x1a-modules/localization/proto/localization.proto\x1a#modules/routing/proto/routing.proto\x1a\x32modules/prediction/proto/prediction_obstacle.proto\"\x8c\x02\n\x16StdPlanningFuzzMessage\x12\'\n\x07\x63hassis\x18\x01 \x02(\x0b\x32\x16.apollo.canbus.Chassis\x12H\n\x15localization_estimate\x18\x02 \x02(\x0b\x32).apollo.localization.LocalizationEstimate\x12\x39\n\x10routing_response\x18\x03 \x02(\x0b\x32\x1f.apollo.routing.RoutingResponse\x12\x44\n\x14prediction_obstacles\x18\x04 \x02(\x0b\x32&.apollo.prediction.PredictionObstacles')
  ,
  dependencies=[modules_dot_canbus_dot_proto_dot_chassis__pb2.DESCRIPTOR,modules_dot_localization_dot_proto_dot_localization__pb2.DESCRIPTOR,modules_dot_routing_dot_proto_dot_routing__pb2.DESCRIPTOR,modules_dot_prediction_dot_proto_dot_prediction__obstacle__pb2.DESCRIPTOR,])




_STDPLANNINGFUZZMESSAGE = _descriptor.Descriptor(
  name='StdPlanningFuzzMessage',
  full_name='apollo.tools.fuzz.planning.StdPlanningFuzzMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chassis', full_name='apollo.tools.fuzz.planning.StdPlanningFuzzMessage.chassis', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='localization_estimate', full_name='apollo.tools.fuzz.planning.StdPlanningFuzzMessage.localization_estimate', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='routing_response', full_name='apollo.tools.fuzz.planning.StdPlanningFuzzMessage.routing_response', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prediction_obstacles', full_name='apollo.tools.fuzz.planning.StdPlanningFuzzMessage.prediction_obstacles', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=530,
)

_STDPLANNINGFUZZMESSAGE.fields_by_name['chassis'].message_type = modules_dot_canbus_dot_proto_dot_chassis__pb2._CHASSIS
_STDPLANNINGFUZZMESSAGE.fields_by_name['localization_estimate'].message_type = modules_dot_localization_dot_proto_dot_localization__pb2._LOCALIZATIONESTIMATE
_STDPLANNINGFUZZMESSAGE.fields_by_name['routing_response'].message_type = modules_dot_routing_dot_proto_dot_routing__pb2._ROUTINGRESPONSE
_STDPLANNINGFUZZMESSAGE.fields_by_name['prediction_obstacles'].message_type = modules_dot_prediction_dot_proto_dot_prediction__obstacle__pb2._PREDICTIONOBSTACLES
DESCRIPTOR.message_types_by_name['StdPlanningFuzzMessage'] = _STDPLANNINGFUZZMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StdPlanningFuzzMessage = _reflection.GeneratedProtocolMessageType('StdPlanningFuzzMessage', (_message.Message,), dict(
  DESCRIPTOR = _STDPLANNINGFUZZMESSAGE,
  __module__ = 'modules.tools.fuzz.planning.proto.std_planning_fuzz_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.fuzz.planning.StdPlanningFuzzMessage)
  ))
_sym_db.RegisterMessage(StdPlanningFuzzMessage)


# @@protoc_insertion_point(module_scope)
