# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/proto/async_fusion_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/proto/async_fusion_config.proto',
  package='apollo.perception.async_fusion_config',
  syntax='proto2',
  serialized_pb=_b('\n2modules/perception/proto/async_fusion_config.proto\x12%apollo.perception.async_fusion_config\"\xc6\x03\n\x0cModelConfigs\x12\x19\n\x04name\x18\x01 \x01(\t:\x0b\x41syncFusion\x12\x16\n\x07version\x18\x02 \x01(\t:\x05\x31.0.0\x12 \n\x0cmatch_method\x18\x03 \x01(\t:\nhm_matcher\x12\x1d\n\x12max_match_distance\x18\x04 \x01(\x02:\x01\x34\x12(\n\x1amax_lidar_invisible_period\x18\x05 \x01(\x02:\x04\x30.25\x12(\n\x1amax_radar_invisible_period\x18\x06 \x01(\x02:\x04\x30.25\x12%\n\x19max_radar_confident_angle\x18\x07 \x01(\x02:\x02\x33\x30\x12(\n\x1cmin_radar_confident_distance\x18\x08 \x01(\x02:\x02\x34\x30\x12\"\n\x14publish_if_has_lidar\x18\t \x01(\x08:\x04true\x12\"\n\x14publish_if_has_radar\x18\n \x01(\x08:\x04true\x12#\n\x0epublish_sensor\x18\x0b \x01(\t:\x0bvelodyne_64\x12\x17\n\tuse_radar\x18\x0c \x01(\x08:\x04true\x12\x17\n\tuse_lidar\x18\r \x01(\x08:\x04true')
)




_MODELCONFIGS = _descriptor.Descriptor(
  name='ModelConfigs',
  full_name='apollo.perception.async_fusion_config.ModelConfigs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apollo.perception.async_fusion_config.ModelConfigs.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("AsyncFusion").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='apollo.perception.async_fusion_config.ModelConfigs.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("1.0.0").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='match_method', full_name='apollo.perception.async_fusion_config.ModelConfigs.match_method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("hm_matcher").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_match_distance', full_name='apollo.perception.async_fusion_config.ModelConfigs.max_match_distance', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_lidar_invisible_period', full_name='apollo.perception.async_fusion_config.ModelConfigs.max_lidar_invisible_period', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.25),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_radar_invisible_period', full_name='apollo.perception.async_fusion_config.ModelConfigs.max_radar_invisible_period', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.25),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_radar_confident_angle', full_name='apollo.perception.async_fusion_config.ModelConfigs.max_radar_confident_angle', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(30),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_radar_confident_distance', full_name='apollo.perception.async_fusion_config.ModelConfigs.min_radar_confident_distance', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(40),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publish_if_has_lidar', full_name='apollo.perception.async_fusion_config.ModelConfigs.publish_if_has_lidar', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publish_if_has_radar', full_name='apollo.perception.async_fusion_config.ModelConfigs.publish_if_has_radar', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publish_sensor', full_name='apollo.perception.async_fusion_config.ModelConfigs.publish_sensor', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("velodyne_64").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_radar', full_name='apollo.perception.async_fusion_config.ModelConfigs.use_radar', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_lidar', full_name='apollo.perception.async_fusion_config.ModelConfigs.use_lidar', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=548,
)

DESCRIPTOR.message_types_by_name['ModelConfigs'] = _MODELCONFIGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelConfigs = _reflection.GeneratedProtocolMessageType('ModelConfigs', (_message.Message,), dict(
  DESCRIPTOR = _MODELCONFIGS,
  __module__ = 'modules.perception.proto.async_fusion_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.async_fusion_config.ModelConfigs)
  ))
_sym_db.RegisterMessage(ModelConfigs)


# @@protoc_insertion_point(module_scope)
