# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/proto/geometry_camera_converter_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/proto/geometry_camera_converter_config.proto',
  package='apollo.perception.geometry_camera_converter_config',
  syntax='proto2',
  serialized_pb=_b('\n?modules/perception/proto/geometry_camera_converter_config.proto\x12\x32\x61pollo.perception.geometry_camera_converter_config\"\xa9\x01\n\x0cModelConfigs\x12%\n\x04name\x18\x01 \x01(\t:\x17GeometryCameraConverter\x12\x16\n\x07version\x18\x02 \x01(\t:\x05\x31.0.0\x12Z\n\x15\x63\x61mera_intrinsic_file\x18\x03 \x01(\t:;modules/perception/data/params/front_camera_intrinsics.yaml')
)




_MODELCONFIGS = _descriptor.Descriptor(
  name='ModelConfigs',
  full_name='apollo.perception.geometry_camera_converter_config.ModelConfigs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apollo.perception.geometry_camera_converter_config.ModelConfigs.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("GeometryCameraConverter").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='apollo.perception.geometry_camera_converter_config.ModelConfigs.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("1.0.0").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='camera_intrinsic_file', full_name='apollo.perception.geometry_camera_converter_config.ModelConfigs.camera_intrinsic_file', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("modules/perception/data/params/front_camera_intrinsics.yaml").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=289,
)

DESCRIPTOR.message_types_by_name['ModelConfigs'] = _MODELCONFIGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelConfigs = _reflection.GeneratedProtocolMessageType('ModelConfigs', (_message.Message,), dict(
  DESCRIPTOR = _MODELCONFIGS,
  __module__ = 'modules.perception.proto.geometry_camera_converter_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.geometry_camera_converter_config.ModelConfigs)
  ))
_sym_db.RegisterMessage(ModelConfigs)


# @@protoc_insertion_point(module_scope)
