# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/proto/hdmap_roi_filter_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/proto/hdmap_roi_filter_config.proto',
  package='apollo.perception.hdmap_roi_filter_config',
  syntax='proto2',
  serialized_pb=_b('\n6modules/perception/proto/hdmap_roi_filter_config.proto\x12)apollo.perception.hdmap_roi_filter_config\"\x88\x01\n\x0cModelConfigs\x12\x1c\n\x04name\x18\x01 \x01(\t:\x0eHdmapROIFilter\x12\x16\n\x07version\x18\x02 \x01(\t:\x05\x31.0.0\x12\x11\n\x05range\x18\x03 \x01(\x01:\x02\x37\x30\x12\x17\n\tcell_size\x18\x04 \x01(\x01:\x04\x30.25\x12\x16\n\x0b\x65xtend_dist\x18\x05 \x01(\x01:\x01\x30')
)




_MODELCONFIGS = _descriptor.Descriptor(
  name='ModelConfigs',
  full_name='apollo.perception.hdmap_roi_filter_config.ModelConfigs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apollo.perception.hdmap_roi_filter_config.ModelConfigs.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("HdmapROIFilter").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='apollo.perception.hdmap_roi_filter_config.ModelConfigs.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("1.0.0").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range', full_name='apollo.perception.hdmap_roi_filter_config.ModelConfigs.range', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(70),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_size', full_name='apollo.perception.hdmap_roi_filter_config.ModelConfigs.cell_size', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.25),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extend_dist', full_name='apollo.perception.hdmap_roi_filter_config.ModelConfigs.extend_dist', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=238,
)

DESCRIPTOR.message_types_by_name['ModelConfigs'] = _MODELCONFIGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelConfigs = _reflection.GeneratedProtocolMessageType('ModelConfigs', (_message.Message,), dict(
  DESCRIPTOR = _MODELCONFIGS,
  __module__ = 'modules.perception.proto.hdmap_roi_filter_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.hdmap_roi_filter_config.ModelConfigs)
  ))
_sym_db.RegisterMessage(ModelConfigs)


# @@protoc_insertion_point(module_scope)
