# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/proto/tracker_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/proto/tracker_config.proto',
  package='apollo.perception.tracker_config',
  syntax='proto2',
  serialized_pb=_b('\n-modules/perception/proto/tracker_config.proto\x12 apollo.perception.tracker_config\"\xcc\x08\n\x0cModelConfigs\x12\x1d\n\x04name\x18\x01 \x01(\t:\x0fHmObjectTracker\x12\x16\n\x07version\x18\x02 \x01(\t:\x05\x31.1.0\x12\x65\n\x0ematcher_method\x18\x03 \x01(\x0e\x32:.apollo.perception.tracker_config.ModelConfigs.MatcherType:\x11HUNGARIAN_MATCHER\x12_\n\rfilter_method\x18\x04 \x01(\x0e\x32\x39.apollo.perception.tracker_config.ModelConfigs.FilterType:\rKALMAN_FILTER\x12,\n!track_cached_history_size_maximum\x18\x05 \x01(\x05:\x01\x35\x12.\n#track_consecutive_invisible_maximum\x18\x06 \x01(\x05:\x01\x31\x12(\n\x1btrack_visible_ratio_minimum\x18\x07 \x01(\x02:\x03\x30.6\x12\x1e\n\x13\x63ollect_age_minimum\x18\x08 \x01(\x05:\x01\x30\x12\x30\n%collect_consecutive_invisible_maximum\x18\t \x01(\x05:\x01\x30\x12%\n\x1a\x61\x63\x63\x65leration_noise_maximum\x18\n \x01(\x02:\x01\x35\x12 \n\x13speed_noise_maximum\x18\x0b \x01(\x02:\x03\x30.4\x12!\n\x16match_distance_maximum\x18\x0c \x01(\x02:\x01\x34\x12%\n\x18location_distance_weight\x18\r \x01(\x02:\x03\x30.6\x12&\n\x19\x64irection_distance_weight\x18\x0e \x01(\x02:\x03\x30.2\x12&\n\x19\x62\x62ox_size_distance_weight\x18\x0f \x01(\x02:\x03\x30.1\x12&\n\x19point_num_distance_weight\x18\x10 \x01(\x02:\x03\x30.1\x12&\n\x19histogram_distance_weight\x18\x11 \x01(\x02:\x03\x30.5\x12\x1e\n\x12histogram_bin_size\x18\x12 \x01(\x05:\x02\x31\x30\x12\x1a\n\x0cuse_adaptive\x18\x13 \x01(\x08:\x04true\x12\x1e\n\x11measurement_noise\x18\x14 \x01(\x02:\x03\x30.4\x12!\n\x16initial_velocity_noise\x18\x15 \x01(\x02:\x01\x35\x12 \n\x14xy_propagation_noise\x18\x16 \x01(\x02:\x02\x31\x30\x12\x1f\n\x13z_propagation_noise\x18\x17 \x01(\x02:\x02\x31\x30\x12\'\n\x1b\x62reakdown_threshold_maximum\x18\x18 \x01(\x02:\x02\x31\x30\"$\n\x0bMatcherType\x12\x15\n\x11HUNGARIAN_MATCHER\x10\x01\"\x1f\n\nFilterType\x12\x11\n\rKALMAN_FILTER\x10\x01')
)



_MODELCONFIGS_MATCHERTYPE = _descriptor.EnumDescriptor(
  name='MatcherType',
  full_name='apollo.perception.tracker_config.ModelConfigs.MatcherType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HUNGARIAN_MATCHER', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1115,
  serialized_end=1151,
)
_sym_db.RegisterEnumDescriptor(_MODELCONFIGS_MATCHERTYPE)

_MODELCONFIGS_FILTERTYPE = _descriptor.EnumDescriptor(
  name='FilterType',
  full_name='apollo.perception.tracker_config.ModelConfigs.FilterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KALMAN_FILTER', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1153,
  serialized_end=1184,
)
_sym_db.RegisterEnumDescriptor(_MODELCONFIGS_FILTERTYPE)


_MODELCONFIGS = _descriptor.Descriptor(
  name='ModelConfigs',
  full_name='apollo.perception.tracker_config.ModelConfigs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apollo.perception.tracker_config.ModelConfigs.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("HmObjectTracker").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='apollo.perception.tracker_config.ModelConfigs.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("1.1.0").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matcher_method', full_name='apollo.perception.tracker_config.ModelConfigs.matcher_method', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_method', full_name='apollo.perception.tracker_config.ModelConfigs.filter_method', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track_cached_history_size_maximum', full_name='apollo.perception.tracker_config.ModelConfigs.track_cached_history_size_maximum', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track_consecutive_invisible_maximum', full_name='apollo.perception.tracker_config.ModelConfigs.track_consecutive_invisible_maximum', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track_visible_ratio_minimum', full_name='apollo.perception.tracker_config.ModelConfigs.track_visible_ratio_minimum', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.6),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collect_age_minimum', full_name='apollo.perception.tracker_config.ModelConfigs.collect_age_minimum', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collect_consecutive_invisible_maximum', full_name='apollo.perception.tracker_config.ModelConfigs.collect_consecutive_invisible_maximum', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acceleration_noise_maximum', full_name='apollo.perception.tracker_config.ModelConfigs.acceleration_noise_maximum', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed_noise_maximum', full_name='apollo.perception.tracker_config.ModelConfigs.speed_noise_maximum', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='match_distance_maximum', full_name='apollo.perception.tracker_config.ModelConfigs.match_distance_maximum', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location_distance_weight', full_name='apollo.perception.tracker_config.ModelConfigs.location_distance_weight', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.6),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction_distance_weight', full_name='apollo.perception.tracker_config.ModelConfigs.direction_distance_weight', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bbox_size_distance_weight', full_name='apollo.perception.tracker_config.ModelConfigs.bbox_size_distance_weight', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_num_distance_weight', full_name='apollo.perception.tracker_config.ModelConfigs.point_num_distance_weight', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='histogram_distance_weight', full_name='apollo.perception.tracker_config.ModelConfigs.histogram_distance_weight', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='histogram_bin_size', full_name='apollo.perception.tracker_config.ModelConfigs.histogram_bin_size', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_adaptive', full_name='apollo.perception.tracker_config.ModelConfigs.use_adaptive', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='measurement_noise', full_name='apollo.perception.tracker_config.ModelConfigs.measurement_noise', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial_velocity_noise', full_name='apollo.perception.tracker_config.ModelConfigs.initial_velocity_noise', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xy_propagation_noise', full_name='apollo.perception.tracker_config.ModelConfigs.xy_propagation_noise', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_propagation_noise', full_name='apollo.perception.tracker_config.ModelConfigs.z_propagation_noise', index=22,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='breakdown_threshold_maximum', full_name='apollo.perception.tracker_config.ModelConfigs.breakdown_threshold_maximum', index=23,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELCONFIGS_MATCHERTYPE,
    _MODELCONFIGS_FILTERTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=1184,
)

_MODELCONFIGS.fields_by_name['matcher_method'].enum_type = _MODELCONFIGS_MATCHERTYPE
_MODELCONFIGS.fields_by_name['filter_method'].enum_type = _MODELCONFIGS_FILTERTYPE
_MODELCONFIGS_MATCHERTYPE.containing_type = _MODELCONFIGS
_MODELCONFIGS_FILTERTYPE.containing_type = _MODELCONFIGS
DESCRIPTOR.message_types_by_name['ModelConfigs'] = _MODELCONFIGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelConfigs = _reflection.GeneratedProtocolMessageType('ModelConfigs', (_message.Message,), dict(
  DESCRIPTOR = _MODELCONFIGS,
  __module__ = 'modules.perception.proto.tracker_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.tracker_config.ModelConfigs)
  ))
_sym_db.RegisterMessage(ModelConfigs)


# @@protoc_insertion_point(module_scope)
