# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/drivers/lidar_velodyne/proto/transform_node_conf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/drivers/lidar_velodyne/proto/transform_node_conf.proto',
  package='apollo.drivers.lidar_velodyne',
  syntax='proto2',
  serialized_pb=_b('\n>modules/drivers/lidar_velodyne/proto/transform_node_conf.proto\x12\x1d\x61pollo.drivers.lidar_velodyne\"\x9b\x01\n\x11TransformNodeConf\x12\x16\n\tmin_range\x18\x01 \x01(\x01:\x03\x30.9\x12\x16\n\tmax_range\x18\x02 \x01(\x01:\x03\x31\x33\x30\x12\x19\n\x0eview_direction\x18\x03 \x01(\x01:\x01\x30\x12#\n\nview_width\x18\x04 \x01(\x01:\x0f\x36.2831853071796\x12\x16\n\x08\x66rame_id\x18\x05 \x01(\t:\x04odom')
)




_TRANSFORMNODECONF = _descriptor.Descriptor(
  name='TransformNodeConf',
  full_name='apollo.drivers.lidar_velodyne.TransformNodeConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_range', full_name='apollo.drivers.lidar_velodyne.TransformNodeConf.min_range', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.9),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_range', full_name='apollo.drivers.lidar_velodyne.TransformNodeConf.max_range', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(130),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_direction', full_name='apollo.drivers.lidar_velodyne.TransformNodeConf.view_direction', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_width', full_name='apollo.drivers.lidar_velodyne.TransformNodeConf.view_width', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(6.2831853071796),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='apollo.drivers.lidar_velodyne.TransformNodeConf.frame_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("odom").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=253,
)

DESCRIPTOR.message_types_by_name['TransformNodeConf'] = _TRANSFORMNODECONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransformNodeConf = _reflection.GeneratedProtocolMessageType('TransformNodeConf', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFORMNODECONF,
  __module__ = 'modules.drivers.lidar_velodyne.proto.transform_node_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.drivers.lidar_velodyne.TransformNodeConf)
  ))
_sym_db.RegisterMessage(TransformNodeConf)


# @@protoc_insertion_point(module_scope)
