# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/navi_generator/proto/simulation_world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/navi_generator/proto/simulation_world.proto',
  package='apollo.navi_generator',
  syntax='proto2',
  serialized_pb=_b('\n9modules/tools/navi_generator/proto/simulation_world.proto\x12\x15\x61pollo.navi_generator\"}\n\x06Object\x12\x0f\n\x07heading\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x12\n\nposition_x\x18\x04 \x01(\x01\x12\x12\n\nposition_y\x18\x05 \x01(\x01\x12\x15\n\rtimestamp_sec\x18\x06 \x01(\x01\"s\n\x0fSimulationWorld\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x14\n\x0csequence_num\x18\x02 \x01(\r\x12\x37\n\x10\x61uto_driving_car\x18\x03 \x01(\x0b\x32\x1d.apollo.navi_generator.Object')
)




_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='apollo.navi_generator.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heading', full_name='apollo.navi_generator.Object.heading', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='apollo.navi_generator.Object.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='apollo.navi_generator.Object.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_x', full_name='apollo.navi_generator.Object.position_x', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_y', full_name='apollo.navi_generator.Object.position_y', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_sec', full_name='apollo.navi_generator.Object.timestamp_sec', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=209,
)


_SIMULATIONWORLD = _descriptor.Descriptor(
  name='SimulationWorld',
  full_name='apollo.navi_generator.SimulationWorld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='apollo.navi_generator.SimulationWorld.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence_num', full_name='apollo.navi_generator.SimulationWorld.sequence_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auto_driving_car', full_name='apollo.navi_generator.SimulationWorld.auto_driving_car', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=326,
)

_SIMULATIONWORLD.fields_by_name['auto_driving_car'].message_type = _OBJECT
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['SimulationWorld'] = _SIMULATIONWORLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
  DESCRIPTOR = _OBJECT,
  __module__ = 'modules.tools.navi_generator.proto.simulation_world_pb2'
  # @@protoc_insertion_point(class_scope:apollo.navi_generator.Object)
  ))
_sym_db.RegisterMessage(Object)

SimulationWorld = _reflection.GeneratedProtocolMessageType('SimulationWorld', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONWORLD,
  __module__ = 'modules.tools.navi_generator.proto.simulation_world_pb2'
  # @@protoc_insertion_point(class_scope:apollo.navi_generator.SimulationWorld)
  ))
_sym_db.RegisterMessage(SimulationWorld)


# @@protoc_insertion_point(module_scope)
