# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/calibration/republish_msg/proto/relative_odometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common.proto import header_pb2 as modules_dot_common_dot_proto_dot_header__pb2
from modules.common.proto import geometry_pb2 as modules_dot_common_dot_proto_dot_geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/calibration/republish_msg/proto/relative_odometry.proto',
  package='apollo.calibration.republish_msg',
  syntax='proto2',
  serialized_pb=_b('\n?modules/calibration/republish_msg/proto/relative_odometry.proto\x12 apollo.calibration.republish_msg\x1a!modules/common/proto/header.proto\x1a#modules/common/proto/geometry.proto\"\xab\x01\n\x10RelativeOdometry\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.apollo.common.Header\x12)\n\x08position\x18\x02 \x01(\x0b\x32\x17.apollo.common.PointENU\x12.\n\x0borientation\x18\x03 \x01(\x0b\x32\x19.apollo.common.Quaternion\x12\x15\n\rposition_type\x18\x04 \x01(\r')
  ,
  dependencies=[modules_dot_common_dot_proto_dot_header__pb2.DESCRIPTOR,modules_dot_common_dot_proto_dot_geometry__pb2.DESCRIPTOR,])




_RELATIVEODOMETRY = _descriptor.Descriptor(
  name='RelativeOdometry',
  full_name='apollo.calibration.republish_msg.RelativeOdometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='apollo.calibration.republish_msg.RelativeOdometry.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='apollo.calibration.republish_msg.RelativeOdometry.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='apollo.calibration.republish_msg.RelativeOdometry.orientation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_type', full_name='apollo.calibration.republish_msg.RelativeOdometry.position_type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=345,
)

_RELATIVEODOMETRY.fields_by_name['header'].message_type = modules_dot_common_dot_proto_dot_header__pb2._HEADER
_RELATIVEODOMETRY.fields_by_name['position'].message_type = modules_dot_common_dot_proto_dot_geometry__pb2._POINTENU
_RELATIVEODOMETRY.fields_by_name['orientation'].message_type = modules_dot_common_dot_proto_dot_geometry__pb2._QUATERNION
DESCRIPTOR.message_types_by_name['RelativeOdometry'] = _RELATIVEODOMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RelativeOdometry = _reflection.GeneratedProtocolMessageType('RelativeOdometry', (_message.Message,), dict(
  DESCRIPTOR = _RELATIVEODOMETRY,
  __module__ = 'modules.calibration.republish_msg.proto.relative_odometry_pb2'
  # @@protoc_insertion_point(class_scope:apollo.calibration.republish_msg.RelativeOdometry)
  ))
_sym_db.RegisterMessage(RelativeOdometry)


# @@protoc_insertion_point(module_scope)
