# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/fuzz/calibration/proto/lidar_ex_checker_fuzz.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.localization.proto import gps_pb2 as modules_dot_localization_dot_proto_dot_gps__pb2
from modules.drivers.gnss.proto import ins_pb2 as modules_dot_drivers_dot_gnss_dot_proto_dot_ins__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/fuzz/calibration/proto/lidar_ex_checker_fuzz.proto',
  package='apollo.tools.fuzz.calibration',
  syntax='proto2',
  serialized_pb=_b('\n@modules/tools/fuzz/calibration/proto/lidar_ex_checker_fuzz.proto\x12\x1d\x61pollo.tools.fuzz.calibration\x1a$modules/localization/proto/gps.proto\x1a$modules/drivers/gnss/proto/ins.proto\"r\n\x19LidarExCheckerFuzzMessage\x12%\n\x03gps\x18\x01 \x02(\x0b\x32\x18.apollo.localization.Gps\x12.\n\x08ins_stat\x18\x02 \x02(\x0b\x32\x1c.apollo.drivers.gnss.InsStat')
  ,
  dependencies=[modules_dot_localization_dot_proto_dot_gps__pb2.DESCRIPTOR,modules_dot_drivers_dot_gnss_dot_proto_dot_ins__pb2.DESCRIPTOR,])




_LIDAREXCHECKERFUZZMESSAGE = _descriptor.Descriptor(
  name='LidarExCheckerFuzzMessage',
  full_name='apollo.tools.fuzz.calibration.LidarExCheckerFuzzMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gps', full_name='apollo.tools.fuzz.calibration.LidarExCheckerFuzzMessage.gps', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ins_stat', full_name='apollo.tools.fuzz.calibration.LidarExCheckerFuzzMessage.ins_stat', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=289,
)

_LIDAREXCHECKERFUZZMESSAGE.fields_by_name['gps'].message_type = modules_dot_localization_dot_proto_dot_gps__pb2._GPS
_LIDAREXCHECKERFUZZMESSAGE.fields_by_name['ins_stat'].message_type = modules_dot_drivers_dot_gnss_dot_proto_dot_ins__pb2._INSSTAT
DESCRIPTOR.message_types_by_name['LidarExCheckerFuzzMessage'] = _LIDAREXCHECKERFUZZMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LidarExCheckerFuzzMessage = _reflection.GeneratedProtocolMessageType('LidarExCheckerFuzzMessage', (_message.Message,), dict(
  DESCRIPTOR = _LIDAREXCHECKERFUZZMESSAGE,
  __module__ = 'modules.tools.fuzz.calibration.proto.lidar_ex_checker_fuzz_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.fuzz.calibration.LidarExCheckerFuzzMessage)
  ))
_sym_db.RegisterMessage(LidarExCheckerFuzzMessage)


# @@protoc_insertion_point(module_scope)
