# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/fuzz/guardian/proto/guardian_fuzz.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.canbus.proto import chassis_pb2 as modules_dot_canbus_dot_proto_dot_chassis__pb2
from modules.monitor.proto import system_status_pb2 as modules_dot_monitor_dot_proto_dot_system__status__pb2
from modules.control.proto import control_cmd_pb2 as modules_dot_control_dot_proto_dot_control__cmd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/fuzz/guardian/proto/guardian_fuzz.proto',
  package='apollo.tools.fuzz.guardian',
  syntax='proto2',
  serialized_pb=_b('\n5modules/tools/fuzz/guardian/proto/guardian_fuzz.proto\x12\x1a\x61pollo.tools.fuzz.guardian\x1a\"modules/canbus/proto/chassis.proto\x1a)modules/monitor/proto/system_status.proto\x1a\'modules/control/proto/control_cmd.proto\"\xac\x01\n\x13GuardianFuzzMessage\x12\'\n\x07\x63hassis\x18\x01 \x02(\x0b\x32\x16.apollo.canbus.Chassis\x12\x33\n\rsystem_status\x18\x02 \x02(\x0b\x32\x1c.apollo.monitor.SystemStatus\x12\x37\n\x0f\x63ontrol_command\x18\x03 \x02(\x0b\x32\x1e.apollo.control.ControlCommand')
  ,
  dependencies=[modules_dot_canbus_dot_proto_dot_chassis__pb2.DESCRIPTOR,modules_dot_monitor_dot_proto_dot_system__status__pb2.DESCRIPTOR,modules_dot_control_dot_proto_dot_control__cmd__pb2.DESCRIPTOR,])




_GUARDIANFUZZMESSAGE = _descriptor.Descriptor(
  name='GuardianFuzzMessage',
  full_name='apollo.tools.fuzz.guardian.GuardianFuzzMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chassis', full_name='apollo.tools.fuzz.guardian.GuardianFuzzMessage.chassis', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_status', full_name='apollo.tools.fuzz.guardian.GuardianFuzzMessage.system_status', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control_command', full_name='apollo.tools.fuzz.guardian.GuardianFuzzMessage.control_command', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=378,
)

_GUARDIANFUZZMESSAGE.fields_by_name['chassis'].message_type = modules_dot_canbus_dot_proto_dot_chassis__pb2._CHASSIS
_GUARDIANFUZZMESSAGE.fields_by_name['system_status'].message_type = modules_dot_monitor_dot_proto_dot_system__status__pb2._SYSTEMSTATUS
_GUARDIANFUZZMESSAGE.fields_by_name['control_command'].message_type = modules_dot_control_dot_proto_dot_control__cmd__pb2._CONTROLCOMMAND
DESCRIPTOR.message_types_by_name['GuardianFuzzMessage'] = _GUARDIANFUZZMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GuardianFuzzMessage = _reflection.GeneratedProtocolMessageType('GuardianFuzzMessage', (_message.Message,), dict(
  DESCRIPTOR = _GUARDIANFUZZMESSAGE,
  __module__ = 'modules.tools.fuzz.guardian.proto.guardian_fuzz_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.fuzz.guardian.GuardianFuzzMessage)
  ))
_sym_db.RegisterMessage(GuardianFuzzMessage)


# @@protoc_insertion_point(module_scope)
