# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/monitor/proto/online_report.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common.vehicle_state.proto import vehicle_state_pb2 as modules_dot_common_dot_vehicle__state_dot_proto_dot_vehicle__state__pb2
from modules.data.proto import static_info_pb2 as modules_dot_data_dot_proto_dot_static__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/monitor/proto/online_report.proto',
  package='apollo.monitor',
  syntax='proto2',
  serialized_pb=_b('\n)modules/monitor/proto/online_report.proto\x12\x0e\x61pollo.monitor\x1a\x36modules/common/vehicle_state/proto/vehicle_state.proto\x1a$modules/data/proto/static_info.proto\"x\n\x12VehicleStateReport\x12.\n\x0cvehicle_info\x18\x01 \x01(\x0b\x32\x18.apollo.data.VehicleInfo\x12\x32\n\rvehicle_state\x18\x02 \x01(\x0b\x32\x1b.apollo.common.VehicleState')
  ,
  dependencies=[modules_dot_common_dot_vehicle__state_dot_proto_dot_vehicle__state__pb2.DESCRIPTOR,modules_dot_data_dot_proto_dot_static__info__pb2.DESCRIPTOR,])




_VEHICLESTATEREPORT = _descriptor.Descriptor(
  name='VehicleStateReport',
  full_name='apollo.monitor.VehicleStateReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle_info', full_name='apollo.monitor.VehicleStateReport.vehicle_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_state', full_name='apollo.monitor.VehicleStateReport.vehicle_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=275,
)

_VEHICLESTATEREPORT.fields_by_name['vehicle_info'].message_type = modules_dot_data_dot_proto_dot_static__info__pb2._VEHICLEINFO
_VEHICLESTATEREPORT.fields_by_name['vehicle_state'].message_type = modules_dot_common_dot_vehicle__state_dot_proto_dot_vehicle__state__pb2._VEHICLESTATE
DESCRIPTOR.message_types_by_name['VehicleStateReport'] = _VEHICLESTATEREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VehicleStateReport = _reflection.GeneratedProtocolMessageType('VehicleStateReport', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLESTATEREPORT,
  __module__ = 'modules.monitor.proto.online_report_pb2'
  # @@protoc_insertion_point(class_scope:apollo.monitor.VehicleStateReport)
  ))
_sym_db.RegisterMessage(VehicleStateReport)


# @@protoc_insertion_point(module_scope)
