# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/tools/fuzz/control/proto/control_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.localization.proto import localization_pb2 as modules_dot_localization_dot_proto_dot_localization__pb2
from modules.control.proto import pad_msg_pb2 as modules_dot_control_dot_proto_dot_pad__msg__pb2
from modules.planning.proto import planning_pb2 as modules_dot_planning_dot_proto_dot_planning__pb2
from modules.canbus.proto import chassis_pb2 as modules_dot_canbus_dot_proto_dot_chassis__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/tools/fuzz/control/proto/control_message.proto',
  package='apollo.tools.fuzz.control',
  syntax='proto2',
  serialized_pb=_b('\n6modules/tools/fuzz/control/proto/control_message.proto\x12\x19\x61pollo.tools.fuzz.control\x1a-modules/localization/proto/localization.proto\x1a#modules/control/proto/pad_msg.proto\x1a%modules/planning/proto/planning.proto\x1a\"modules/canbus/proto/chassis.proto\"\xd9\x01\n\x12\x43ontrolFuzzMessage\x12?\n\x0clocalization\x18\x01 \x02(\x0b\x32).apollo.localization.LocalizationEstimate\x12\'\n\x03pad\x18\x02 \x02(\x0b\x32\x1a.apollo.control.PadMessage\x12\x30\n\x08planning\x18\x03 \x02(\x0b\x32\x1e.apollo.planning.ADCTrajectory\x12\'\n\x07\x63hassis\x18\x04 \x02(\x0b\x32\x16.apollo.canbus.Chassis')
  ,
  dependencies=[modules_dot_localization_dot_proto_dot_localization__pb2.DESCRIPTOR,modules_dot_control_dot_proto_dot_pad__msg__pb2.DESCRIPTOR,modules_dot_planning_dot_proto_dot_planning__pb2.DESCRIPTOR,modules_dot_canbus_dot_proto_dot_chassis__pb2.DESCRIPTOR,])




_CONTROLFUZZMESSAGE = _descriptor.Descriptor(
  name='ControlFuzzMessage',
  full_name='apollo.tools.fuzz.control.ControlFuzzMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localization', full_name='apollo.tools.fuzz.control.ControlFuzzMessage.localization', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pad', full_name='apollo.tools.fuzz.control.ControlFuzzMessage.pad', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='planning', full_name='apollo.tools.fuzz.control.ControlFuzzMessage.planning', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chassis', full_name='apollo.tools.fuzz.control.ControlFuzzMessage.chassis', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=462,
)

_CONTROLFUZZMESSAGE.fields_by_name['localization'].message_type = modules_dot_localization_dot_proto_dot_localization__pb2._LOCALIZATIONESTIMATE
_CONTROLFUZZMESSAGE.fields_by_name['pad'].message_type = modules_dot_control_dot_proto_dot_pad__msg__pb2._PADMESSAGE
_CONTROLFUZZMESSAGE.fields_by_name['planning'].message_type = modules_dot_planning_dot_proto_dot_planning__pb2._ADCTRAJECTORY
_CONTROLFUZZMESSAGE.fields_by_name['chassis'].message_type = modules_dot_canbus_dot_proto_dot_chassis__pb2._CHASSIS
DESCRIPTOR.message_types_by_name['ControlFuzzMessage'] = _CONTROLFUZZMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlFuzzMessage = _reflection.GeneratedProtocolMessageType('ControlFuzzMessage', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLFUZZMESSAGE,
  __module__ = 'modules.tools.fuzz.control.proto.control_message_pb2'
  # @@protoc_insertion_point(class_scope:apollo.tools.fuzz.control.ControlFuzzMessage)
  ))
_sym_db.RegisterMessage(ControlFuzzMessage)


# @@protoc_insertion_point(module_scope)
